# Generated by Django 2.2.28 on 2023-08-23 20:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campusonline", "0073_person_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonRoom",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="campusonline.Person",
                    ),
                ),
                ("modified", models.DateTimeField()),
                ("url", models.URLField()),
                ("sip", models.EmailField(max_length=254)),
                (
                    "call_in",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
